"""Three-way evaluation: rules engine vs full policy workflow vs this prototype (both arms).

Reads (never writes) the fresh rule-based baseline in baseline/, the full policy workflow
prototype's existing results, and this project's runs/results.jsonl; writes
runs/eval-summary.json, runs/comparison.csv, runs/disagreements.md,
runs/cost-summary.json and runs/retrieval-quality.md.

CLI:  uv run python -m src.evaluate
"""

import json
import re
from datetime import datetime, timezone

from . import config

# Documented expectations from samples/eval-tuples.md (copied as data — clean-room rule).
# basis "core": an Existing tuple row names the persona and its expected application result.
# basis "derived": the doc's "existing variants" section equates the persona with a core tuple.
EXPECTED = {
    "felix-brandt":       ("ELIGIBLE", "core", "tuple 1"),
    "sofia-lorenz":       ("ELIGIBLE", "core", "tuple 2"),
    "erika-musterfrau":   ("ELIGIBLE", "core", "tuple 5"),
    "jonas-krause":       ("MISSING_INFORMATION", "core", "tuple 7"),
    "claudia-siebert":    ("ELIGIBLE", "core", "tuple 9"),
    "stefan-brenner":     ("MANUAL_REVIEW", "core", "tuple 12"),
    "katrin-vogel":       ("MANUAL_REVIEW", "core", "tuple 16"),
    "tobias-falk":        ("INELIGIBLE", "core", "tuple 17"),
    "tobias-renner":      ("MISSING_INFORMATION", "core", "tuple 18"),
    "anna-beispiel":      ("MISSING_INFORMATION", "derived", "repeats tuple 7"),
    "max-mustermann":     ("MISSING_INFORMATION", "derived", "repeats tuple 7"),
    "lena-schmidt-weber": ("MISSING_INFORMATION", "derived", "repeats tuple 7"),
    "melina-sturm":       ("MISSING_INFORMATION", "derived", "variant of tuple 18"),
    "oemer-yilmaz":       ("ELIGIBLE", "derived", "second complete FHR (tuple 5)"),
}


# --- Pure metric helpers (the tested seam) ---------------------------------------
def modal(values: list[str]) -> str | None:
    """Most frequent value; deterministic tie-break by sorted order."""
    if not values:
        return None
    return max(sorted(set(values)), key=values.count)


def flipped(values: list[str]) -> bool | None:
    """Did repeated runs on identical input disagree? None without >=2 runs."""
    if len(values) < 2:
        return None
    return len(set(values)) > 1


def accuracy(pairs: list[tuple[str | None, str | None]]) -> float | None:
    """Fraction of (predicted, expected) pairs that match, over pairs where both exist."""
    scored = [(p, e) for p, e in pairs if p is not None and e is not None]
    if not scored:
        return None
    return round(sum(p == e for p, e in scored) / len(scored), 3)


def normalize_title(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", title.lower()).strip()


# --- Loaders ---------------------------------------------------------------------
def load_baseline() -> dict:
    """Rule-based results regenerated by baseline.sh (fresh `admissions screen` runs)."""
    rows = {}
    if not config.BASELINE_DIR.exists():
        return rows
    for d in sorted(p for p in config.BASELINE_DIR.iterdir() if p.is_dir()):
        result = d / "application-result.json"
        failure = d / "processing-failure.json"
        if result.exists():
            j = json.loads(result.read_text())
            rows[d.name] = {
                "status": j["application_status"],
                "reason": j["application_reason_code"],
                "headline": j["summary"]["canonical"]["headline"],
            }
        elif failure.exists():
            j = json.loads(failure.read_text())
            rows[d.name] = {"status": "RUN_FAILED", "reason": j.get("code", "UNKNOWN"), "headline": ""}
    return rows


def load_naive() -> dict:
    """Naive prototype statuses per persona (critic-off records), from its existing runs."""
    statuses: dict[str, list[str]] = {}
    if config.NAIVE_RESULTS_PATH.exists():
        for line in config.NAIVE_RESULTS_PATH.open():
            r = json.loads(line)
            if not r["critic_enabled"]:
                statuses.setdefault(r["persona"], []).append(r["application_status"])
    return statuses


def load_ours() -> dict:
    """This prototype's records, keyed (persona, arm) -> list of records ordered by repeat.

    Deduplicated per (persona, repeat, arm) keeping the latest line, so records from
    a --force re-run replace their predecessors instead of double-counting.
    """
    latest: dict[tuple[str, int, str], dict] = {}
    if config.RESULTS_PATH.exists():
        for line in config.RESULTS_PATH.open():
            r = json.loads(line)
            latest[(r["persona"], r["repeat"], r["arm"])] = r
    rows: dict[tuple[str, str], list[dict]] = {}
    for (persona, _, arm), r in latest.items():
        rows.setdefault((persona, arm), []).append(r)
    for records in rows.values():
        records.sort(key=lambda r: r["repeat"])
    return rows


# --- Cost ------------------------------------------------------------------------
def _ledger_totals(path, group_key) -> dict:
    groups: dict[str, dict] = {}
    if path.exists():
        for line in path.open():
            entry = json.loads(line)
            key = group_key(entry)
            if key is None:
                continue
            g = groups.setdefault(key, {"calls": 0, "input_tokens": 0, "output_tokens": 0, "duration_ms": 0})
            g["calls"] += 1
            g["input_tokens"] += entry.get("input_tokens") or 0
            g["output_tokens"] += entry.get("output_tokens") or 0
            g["duration_ms"] += entry.get("duration_ms") or 0
    return groups


def rules_cost() -> dict:
    """Extraction cost of the fresh baseline, from each run's application-facts.json attempts."""
    total = {"calls": 0, "input_tokens": 0, "output_tokens": 0, "duration_ms": 0}
    for d in sorted(config.BASELINE_DIR.glob("*/application-facts.json")):
        facts = json.loads(d.read_text())
        for doc in facts.get("documents", []):
            for attempt in doc.get("attempts", []):
                total["calls"] += 1
                total["input_tokens"] += attempt.get("input_tokens") or 0
                total["output_tokens"] += attempt.get("output_tokens") or 0
                total["duration_ms"] += attempt.get("duration_ms") or 0
    return total


# --- Retrieval quality -----------------------------------------------------------
def retrieval_quality() -> list[str]:
    """Compile-time retrieval per arm vs the rule-extractor navigation-trace ground truth.

    Ground-truth units are chapter-level titles; an arm covers one if it opened that
    section or any section inside the chapter's span (its ### subsections).
    """
    from .policy_index import PolicyIndex

    lines = ["# Retrieval quality — compile-time section selection vs ground truth", ""]
    if not config.NAV_TRACE_GROUND_TRUTH.exists():
        return lines + ["Ground-truth trace not found; skipped."]
    trace = json.loads(config.NAV_TRACE_GROUND_TRUTH.read_text())
    gt_titles = [t for turn in trace for t in turn.get("opened", [])]
    index = PolicyIndex.from_file()
    # all_sections: ground-truth titles include heading-only ## chapters that the
    # retrieval inventory drops (they live on as breadcrumbs).
    by_norm = {normalize_title(s.title): s for s in index.all_sections}

    # Chapter span per ground-truth title: heading to the next same-or-higher-level heading.
    def span_of(section):
        following = [s for s in index.all_sections if s.start > section.start and s.level <= section.level]
        end = min((s.start for s in following), default=len(index.text))
        return section.start, end

    lines += [f"Ground truth: {len(gt_titles)} sections opened by the rule-extractor "
              f"(`rule-extractor/artifacts/navigation-trace.json`).", ""]
    for arm in config.ARMS:
        path = config.CRITERIA_DIR / f"{arm}.json"
        lines.append(f"## ARM_{arm.upper()}")
        lines.append("")
        if not path.exists():
            lines += ["No compiled criteria artifact yet.", ""]
            continue
        artifact = json.loads(path.read_text())
        opened = [index._by_id[sid] for sid in artifact["opened_section_ids"] if sid in index._by_id]
        gt_spans = []
        covered, missed = [], []
        for title in gt_titles:
            section = by_norm.get(normalize_title(title))
            if section is None:
                missed.append(f"{title} (title not found in index)")
                continue
            start, end = span_of(section)
            gt_spans.append((start, end))
            if any(start <= o.start < end for o in opened):
                covered.append(title)
            else:
                missed.append(title)
        in_gt = [o for o in opened if any(start <= o.start < end for start, end in gt_spans)]
        recall = round(len(covered) / len(gt_titles), 3) if gt_titles else None
        precision = round(len(in_gt) / len(opened), 3) if opened else None
        lines += [
            f"- opened {len(opened)} sections over {len(artifact['nav_trace'])} turn(s), "
            f"coverage_complete={artifact['coverage_complete']}",
            f"- recall vs ground truth: **{recall}** ({len(covered)}/{len(gt_titles)})",
            f"- precision (opened sections inside ground-truth chapters): **{precision}** ({len(in_gt)}/{len(opened)})",
            f"- missed ground-truth sections: {missed or 'none'}",
            "",
        ]
    return lines


# --- Main ------------------------------------------------------------------------
def main() -> None:
    import pandas as pd

    baseline = load_baseline()
    naive = load_naive()
    ours = load_ours()
    personas = sorted(p.name for p in config.SAMPLES_DIR.iterdir() if p.is_dir())

    rows = []
    for persona in personas:
        exp = EXPECTED.get(persona)
        naive_statuses = naive.get(persona, [])
        row = {
            "persona": persona,
            "expected": exp[0] if exp else None,
            "basis": exp[1] if exp else None,
            "rules_status": baseline.get(persona, {}).get("status"),
            "naive_modal": modal(naive_statuses),
            "naive_flipped": flipped(naive_statuses),
        }
        for arm in config.ARMS:
            records = ours.get((persona, arm), [])
            statuses = [r["application_status"] for r in records]
            critic = [r["critic"] for r in records]
            row[f"{arm}_statuses"] = statuses
            row[f"{arm}_modal"] = modal(statuses)
            row[f"{arm}_flipped"] = flipped(statuses)
            row[f"{arm}_critic_retries"] = sum(1 for c in critic if c["retried"])
            row[f"{arm}_critic_unresolved"] = sum(1 for c in critic if c["critic_unresolved"])
        rows.append(row)
    df = pd.DataFrame(rows)

    systems = {"rules": "rules_status", "naive": "naive_modal",
               **{arm: f"{arm}_modal" for arm in config.ARMS}}

    def acc_over(frame, col):
        return accuracy(list(zip(frame[col], frame["expected"])))

    labeled = df[df.expected.notna()]
    core = labeled[labeled.basis == "core"]
    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": config.MODEL,
        "n_personas": len(df),
        "accuracy_core": {name: acc_over(core, col) for name, col in systems.items()},
        "accuracy_all_labeled": {name: acc_over(labeled, col) for name, col in systems.items()},
        "agreement_vs_rules": {},
        "stability": {},
        "critic": {},
    }
    for name, col in systems.items():
        if name == "rules":
            continue
        both = df[df[col].notna() & df.rules_status.notna()]
        summary["agreement_vs_rules"][name] = (
            round(float((both[col] == both.rules_status).mean()), 3) if len(both) else None
        )
    for name, col in [("naive", "naive_flipped")] + [(a, f"{a}_flipped") for a in config.ARMS]:
        flips = df[col].dropna()
        summary["stability"][name] = {
            "personas_with_flips": int(flips.sum()) if len(flips) else None,
            "flip_rate": round(float(flips.mean()), 3) if len(flips) else None,
        }
    summary["stability"]["rules"] = {"personas_with_flips": 0, "flip_rate": 0.0,
                                     "note": "deterministic evaluator, 0 by construction"}
    for arm in config.ARMS:
        records = [r for (_, a), recs in ours.items() if a == arm for r in recs]
        outcomes = [r["critic"] for r in records]
        changed = sum(1 for c, r in ((o, r) for o, r in zip(outcomes, records) if o["retried"])
                      if c["status_before_retry"] != r["application_status"])
        summary["critic"][arm] = {
            "runs": len(records),
            "approved_first": sum(1 for c in outcomes if c["approved_first"]),
            "retried": sum(1 for c in outcomes if c["retried"]),
            "resolved": sum(1 for c in outcomes if c.get("resolved")),
            "unresolved": sum(1 for c in outcomes if c["critic_unresolved"]),
            "status_changed_by_retry": changed,
        }

    # Cost: this project's ledger (by arm+node), naive ledger, rules extraction attempts.
    summary["cost"] = {
        "ours_by_arm_node": _ledger_totals(config.LEDGER_PATH,
                                           lambda e: f"{e.get('arm', '-')}/{e['node']}"),
        "naive_total": _ledger_totals(config.NAIVE_LEDGER_PATH, lambda e: "naive").get("naive"),
        "rules_baseline_total": rules_cost(),
    }

    config.RUNS_DIR.mkdir(parents=True, exist_ok=True)
    (config.RUNS_DIR / "eval-summary.json").write_text(json.dumps(summary, indent=2))
    out = df.copy()
    for arm in config.ARMS:
        out[f"{arm}_statuses"] = out[f"{arm}_statuses"].apply(lambda s: "|".join(s))
    out.to_csv(config.RUNS_DIR / "comparison.csv", index=False)
    (config.RUNS_DIR / "cost-summary.json").write_text(json.dumps(summary["cost"], indent=2))

    # Disagreements: any persona where expected and the four systems do not coincide.
    lines = ["# Disagreements — manual adjudication", "",
             f"Generated {summary['generated_at']} · model {config.MODEL}", ""]
    n = 0
    for _, row in df.iterrows():
        verdicts = {v for v in [row.expected, row.rules_status, row.naive_modal,
                                *[row[f"{a}_modal"] for a in config.ARMS]] if v is not None}
        if len(verdicts) <= 1:
            continue
        n += 1
        lines += [f"## {row.persona}", "",
                  f"- expected: **{row.expected or '(unlabeled)'}** ({row.basis or '-'})",
                  f"- rules engine: **{row.rules_status}** — {baseline.get(row.persona, {}).get('headline', '')}",
                  f"- full policy workflow: **{row.naive_modal}**"]
        for arm in config.ARMS:
            records = ours.get((row.persona, arm), [])
            latest = records[-1] if records else None
            lines.append(f"- ARM_{arm.upper()}: **{row[f'{arm}_modal']}** across {row[f'{arm}_statuses']}"
                         f" (retries {row[f'{arm}_critic_retries']}, unresolved {row[f'{arm}_critic_unresolved']})")
            if latest:
                lines.append(f"  - rationale (latest): {latest['decision']['rationale']}")
        lines += ["- adjudication: _(fill in: which system is right, and why)_", ""]
    if n == 0:
        lines.append("No disagreements with the available data.")
    (config.RUNS_DIR / "disagreements.md").write_text("\n".join(lines))

    (config.RUNS_DIR / "retrieval-quality.md").write_text("\n".join(retrieval_quality()))

    print(json.dumps({k: v for k, v in summary.items() if k != "cost"}, indent=2))
    print(f"\n{n} disagreement(s)")
    print(f"wrote eval-summary.json, comparison.csv, cost-summary.json, "
          f"disagreements.md, retrieval-quality.md -> {config.RUNS_DIR}")


if __name__ == "__main__":
    main()
